name: Backup Discussion

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}

    steps:
      # Step 1: Checkout discussion.json
      - name: Checkout discussion.json
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            discussion.json
          sparse-checkout-cone-mode: false

      # Step 2: Fetch, process and save discussions
      - name: Fetch, process, and save discussions
        run: |
          echo "Fetching discussions from GitHub API..."

          # Fetch discussions from GitHub API
          discussions=$(gh api graphql --paginate --slurp -f query='
            query($owner: String!, $repo: String!, $endCursor: String) {
              repository(owner: $owner, name: $repo) {
                discussions(first: 100, after: $endCursor) {
                  nodes {
                    id
                    title
                    body
                    number
                    labels(first: 10) { nodes { id name url } }
                    category { id name slug emoji emojiHTML }
                    author { login }
                    authorAssociation
                    createdAt
                    updatedAt
                    repository { id url }
                    url
                  }
                  pageInfo {
                    hasNextPage
                    endCursor
                  }
                }
              }
            }' -F owner=$OWNER -F repo=$REPO | jq '
            [.[].data.repository.discussions.nodes[]]
            | map(select(.authorAssociation == "OWNER"))
            | map(select(.category.slug == "announcements" or .category.slug == "show-and-tell"))
            | sort_by(.updatedAt) | reverse
            | unique_by(.id)
            // []'
          )

          echo "Discussions fetched: $(echo "$discussions" | jq length)"
          
          # Debug: Print the discussions to ensure it's populated correctly
          echo "$discussions" | jq .

          if [ "$(echo "$discussions" | jq 'length')" -eq 0 ]; then
            echo "No discussions found"
            exit 1
          fi

          # Merge with existing data if discussion.json exists
          if [ -f "discussion.json" ]; then
            echo "Merging fetched discussions with existing data..."

            createdAtMap=$(jq 'map({(.id): .createdAt}) | add' "discussion.json")

            discussions=$(jq --argjson createdAtMap "$createdAtMap" '
              map(
                if $createdAtMap[.id] then
                  .createdAt = $createdAtMap[.id]
                else
                  .
                end
              )
            ' <<< "$discussions")

            echo "Updated discussions with existing data"
          fi

          # Add file paths to the discussions
          discussions=$(echo "$discussions" | jq '
            map(
              . + {
                jsonFilePath: ("discussions/" + (.number | tostring) + "-" + (.id | tostring) + ".json"),
                markdownFilePath: (
                  if .category.slug == "announcements" then
                    "announcements/" + (.number | tostring) + "-" + (.id | tostring) + ".md"
                  else
                    (.createdAt | fromdate | strftime("%Y")) + "/" +
                    ((.createdAt | fromdate | strftime("%m") | tonumber) | tostring) + "/" +
                    (.number | tostring) + "-" + (.id | tostring) + ".md"
                  end
                )
              }
            )
          ')

          # Debug: Print the processed discussions to check the final result
          echo "Processed discussions: $(echo "$discussions" | jq length)"
          
          # Save the processed discussions to the file
          echo "$discussions" > discussion.json
          echo "Backup completed, saved discussions to discussion.json"

      # Step 3: Verify saved discussions
      - name: Verify saved discussions
        run: |
          echo "Listing files and displaying content of discussion.json"
          ls
          cat discussion.json
