name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auto-correct Markdown files
        uses: huacnlee/autocorrect-action@v2
        with:
          args: --fix '**/*.md'

      - name: Lint and fix Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          fix: true
          globs: '**/*.md'
        continue-on-error: true

      - name: Commit and Push Changes
        run: |
          echo "Starting the commit and push process..."

          # Configure Git user for commit
          echo "Configuring Git user for commit..."
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Add the necessary files to the staging area
          echo "Staging changes for commit..."
          git add discussion.json discussions announcements $(find . -type d -regex './[0-9]+' -exec echo {} \;)

          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit. Skipping commit and push."
            exit 0
          fi

          # Commit the changes
          echo "Committing changes to the repository..."
          git commit -m "chore: format markdown files"

          # Push the changes to the remote repository
          echo "Pushing changes to the remote repository..."
          git push

          echo "Changes committed and pushed successfully."