name: Format Markdown

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
    workflow_dispatch:

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Check for Changed Markdown Files
              uses: tj-actions/changed-files@v42
              id: changed-files
              with:
                  files: '**/*.md'
                  separator: ','
            - name: Run MarkdownLint
              uses: DavidAnson/markdownlint-cli2-action@v15
              if: steps.changed-files.outputs.any_changed == 'true'
              with:
                  globs: ${{ steps.changed-files.outputs.all_changed_files }}
                  separator: ','
                  fix: true
            - name: Commit and Push Changes
              run: |
                  # Configure git
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  # Stage changes, including discussions and folders with numeric names
                  git add discussions blog_data.json README.md SUMMARY.md $(find . -type d -regex './[0-9]+' -exec echo {} \;)
                  # Commit and push changes to the same branch
                  git commit -m "Sync discussions to repo" && git push origin HEAD:${{ github.ref }}
