name: Format Markdown

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
    workflow_dispatch:

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Check for Changed Markdown Files
              uses: tj-actions/changed-files@v42
              id: changed-files
              with:
                  files: '**/*.md'
                  separator: ','
                  
            - name: Run MarkdownLint
              uses: DavidAnson/markdownlint-cli2-action@v15
              if: steps.changed-files.outputs.any_changed == 'true'
              with:
                  config: '.markdownlint.json'
                  globs: ${{ steps.changed-files.outputs.all_changed_files }}
                  separator: ','
                  fix: true
              continue-on-error: true

            - name: Commit and Push Changes
              if: steps.changed-files.outputs.any_changed == 'true'
              env:
                  ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
              run: |
                  # Configure git
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  # Stage changes
                  for file in ${ALL_CHANGED_FILES}; do
                    git add $file
                  done
                  # Commit and push changes to the same branch
                  git commit -m "Format changed markdown files" && git push origin HEAD:${{ github.ref }}
