name: Markdown Lint

on:
    workflow_dispatch:
    schedule:
        - cron: '0 18 * * *'

jobs:
    markdown_lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Lint markdown files
              uses: DavidAnson/markdownlint-cli2-action@v15
              with:
                config: '.markdownlint.json'
                globs: |
                    **/*.md
                    !**/node_modules
                fix: true

            - name: Commit and push changes
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add discussions blog_data.json README.md SUMMARY.md Announcements $(find . -type d -regex './[0-9]+' -exec echo {} \;)
                git diff-index --quiet HEAD || git commit -m "style: lint markdown files"
                git push origin HEAD:${{ github.ref }}