name: Sync Disscussions Workflow

on: workflow_dispatch

jobs:
  sync_disscussions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          npm install @octokit/graphql
          npm install dayjs
      - name: Run Sync Disscussions Script
        run: node .github/workflows/sync_disscussions.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean Files
        run: |
          # Enable extended globbing for advanced pattern matching
          shopt -s extglob

          # # Remove all content in the current directory except for specified files and directories
          rm -r !(.git|.github|discussions|README.md|SUMMARY.md|archive_data.json|[0-9]*)

          # List the contents of the current directory
          ls
      - name: Commit and Push Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Sync disscussions to repo"
          git push origin HEAD:${{ github.ref }}
