name: Sync Discussion To Repo

on:
    workflow_dispatch:

jobs:
    sync_discussion:
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node.js Environment
              uses: actions/setup-node@v4

            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Run Sync Discussions Script
              run: |
                  # Install dependencies and run the script
                  npm install && node scripts/sync_discussions/sync_discussions.js
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Format Markdown Files
              uses: DavidAnson/markdownlint-cli2-action@v15
              with:
                  config: '.markdownlint.json'
                  globs: |
                      **/*.md
                      !**/node_modules
                  fix: true
              continue-on-error: true

            - name: Commit and Push Changes
              run: |
                  # Configure git
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  # Stage changes, including discussions and folders with numeric names
                  git add discussions blog_data.json README.md SUMMARY.md Announcements $(find . -type d -regex './[0-9]+' -exec echo {} \;)
                  # Commit and push changes to the same branch
                  git commit -m "Sync discussions to repo" && git push origin HEAD:${{ github.ref }}
              continue-on-error: true
